language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

script:
  - go build -mod=vendor
  - diff -u <(echo -n) <(gofmt -d $(find . -type f -name "*.go" ! -path "./vendor/*"))
  - go test -v ./...
